name: Sugestie sau întrebare
description: O idee de îmbunătățire sau o nelămurire
title: "[Sugestie] "
labels: ["sugestie"]
body:
  - type: textarea
    id: descriere
    attributes:
      label: Despre ce e vorba
      description: Descrie ideea sau întrebarea.
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: La ce ți-ar folosi? Ce problemă ar rezolva?
